<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <Platforms>AnyCPU;x64</Platforms>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ApplicationIcon>favicon.ico</ApplicationIcon>
    <Version>1.4.5</Version>
  </PropertyGroup>

  <!-- App icon and BluRay MPLS parser -->
  <ItemGroup>
    <Resource Include="favicon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ChapterTool.Core" Version="23.3.0" />
  </ItemGroup>

</Project>
