namespace OneColumnEncoder.Models;

public class AppConfLangProviderM
{
    private static readonly Dictionary<string, Dictionary<string, string>> Data = new()
    {
        ["en"] = new()
        {
            ["AppConf.Overwrite"] = "Overwrite Handling",
            ["AppConf.Language"] = "Language/\u8BED\u8A00",
            ["AppConf.InitMode"] = "Init Mode",
            ["AppConf.Bypass"] = "Default Bypass",
            ["Setting.InitMode.IsFirstLaunch"] = "Auto-import tools on next launch",
            ["Setting.Bypass.SrcValidationGroup"] = "Always bypass Source Validation Checklists",
            ["Setting.Bypass.EncTermsValidationGroup"] = "Always bypass Encoding Terms Validation Group",
            ["AppConf.Cancel"] = "Cancel",
            ["AppConf.Save"] = "Save",
            ["AppConf.ClearOldQueueJson"] = "Clean Old Queue Data",
            ["AppConf.ClearOldQueueJsonTitle"] = "Clean Old Queue Data",
            ["AppConf.ClearOldQueueJsonResult"] = "Deleted {0} old queue file(s).",
            ["AppConf.NoOldQueueJson"] = "No queue data found.",
            ["AppConfModal.Title"] = "1cenc Settings",
            ["AppConfModal.Header"] = "Settings",
            ["Setting.Overwrite.LongPressDivisor"] = "Long Press Dur. MB Divisor (MBtoOW÷Div=mm:ss)",
            ["Setting.Overwrite.MinLongPress"] = "Minimum Long Press Duration (ms)",
            ["Setting.Overwrite.MaxLongPress"] = "Maximum Long Press Duration (ms)",
            ["Setting.Language.Select"] = "Select Language",
            ["AppConf.Validation.Required"] = "{0} is required.",
            ["AppConf.Validation.IntegerOnly"] = "{0} must be an integer.",
            ["AppConf.Validation.Min"] = "{0} must be >= {1}.",
            ["AppConf.Validation.Max"] = "{0} must be <= {1}.",
            ["AppConf.Validation.InvalidNumericInput"] = "Only numeric values are allowed.",
            ["AppConf.Validation.InvalidNumericInputTitle"] = "Invalid Input",
            ["Hint.AppConfNotificationPolicy"] = "Notification features are intentionally unprovided—Evidences suggested phone notif. may lower neural activity that correlates cognitive control: Upshaw, J.D., Shields, G.S., Judah, M.R., & Zabelina, D.L. (2023). Electrophysiological Effects of Smartphone Notifications on Cognitive Control following a Brief Mindfulness Induction. Biological psychology, 108725\r\n",
        },
        ["zh-cn"] = new()
        {
            ["AppConf.Overwrite"] = "文件覆盖确认行为",
            ["AppConf.Language"] = "语言/Language",
            ["AppConf.InitMode"] = "初始化模式",
            ["AppConf.Bypass"] = "默认绕过",
            ["Setting.InitMode.IsFirstLaunch"] = "下次打开尝试自动导入工具",
            ["Setting.Bypass.SrcValidationGroup"] = "默认绕过视频源检查列表",
            ["Setting.Bypass.EncTermsValidationGroup"] = "默认绕过开始压制前提",
            ["AppConf.Cancel"] = "取消",
            ["AppConf.Save"] = "保存",
            ["AppConf.ClearOldQueueJson"] = "清除旧队列数据",
            ["AppConf.ClearOldQueueJsonTitle"] = "清除旧队列数据",
            ["AppConf.ClearOldQueueJsonResult"] = "已删除 {0} 个旧队列文件。",
            ["AppConf.NoOldQueueJson"] = "未找到队列数据。",
            ["AppConfModal.Title"] = "1cenc 设置",
            ["AppConfModal.Header"] = "设置",
            ["Setting.Overwrite.LongPressDivisor"] = "长按兆字节除数（被覆盖文件大小/?MB = 时长）",
            ["Setting.Overwrite.MinLongPress"] = "最小长按持续时间（毫秒）",
            ["Setting.Overwrite.MaxLongPress"] = "最大长按持续时间（毫秒）",
            ["AppConf.Validation.Required"] = "{0} 不能为空。",
            ["AppConf.Validation.IntegerOnly"] = "{0} 必须是整数。",
            ["AppConf.Validation.Min"] = "{0} 必须大于或等于 {1}。",
            ["AppConf.Validation.Max"] = "{0} 必须小于或等于 {1}。",
            ["AppConf.Validation.InvalidNumericInput"] = "只允许输入数字。",
            ["AppConf.Validation.InvalidNumericInputTitle"] = "输入无效",
            ["Setting.Language.Select"] = "选择语言",
            ["Hint.AppConfNotificationPolicy"] = "本应用有意不提供通知功能——研究结果表明，智能手机通知可能会降低与认知控制功能相关的脑神经活动：Upshaw, J.D., Shields, G.S., Judah, M.R., & Zabelina, D.L. (2023). Electrophysiological Effects of Smartphone Notifications on Cognitive Control following a Brief Mindfulness Induction. Biological psychology, 108725",
        },
        ["zh-tw"] = new()
        {
            ["AppConf.Overwrite"] = "文件覆蓋確認行為",
            ["AppConf.Language"] = "語言/Language",
            ["AppConf.InitMode"] = "初始化模式",
            ["AppConf.Bypass"] = "默認繞過",
            ["Setting.InitMode.IsFirstLaunch"] = "下次打開嘗試自動導入工具",
            ["Setting.Bypass.SrcValidationGroup"] = "默認繞過影片源檢查列表",
            ["Setting.Bypass.EncTermsValidationGroup"] = "默認繞過開始壓制前提",
            ["AppConf.Cancel"] = "取消",
            ["AppConf.Save"] = "保存",
            ["AppConf.ClearOldQueueJson"] = "清除舊佇列資料",
            ["AppConf.ClearOldQueueJsonTitle"] = "清除舊佇列資料",
            ["AppConf.ClearOldQueueJsonResult"] = "已刪除 {0} 個舊佇列檔案。",
            ["AppConf.NoOldQueueJson"] = "未找到佇列資料。",
            ["AppConfModal.Title"] = "1cenc 設置",
            ["AppConfModal.Header"] = "設置",
            ["Setting.Overwrite.LongPressDivisor"] = "長按百萬位元組除數（被覆蓋檔案大小/?MB = 時長）",
            ["Setting.Overwrite.MinLongPress"] = "最小長按持續時間（毫秒）",
            ["Setting.Overwrite.MaxLongPress"] = "最大長按持續時間（毫秒）",
            ["AppConf.Validation.Required"] = "{0} 為必填欄位。",
            ["AppConf.Validation.IntegerOnly"] = "{0} 必須是整數。",
            ["AppConf.Validation.Min"] = "{0} 必須大於或等於 {1}。",
            ["AppConf.Validation.Max"] = "{0} 必須小於或等於 {1}。",
            ["AppConf.Validation.InvalidNumericInput"] = "只允許輸入數字。",
            ["AppConf.Validation.InvalidNumericInputTitle"] = "輸入無效",
            ["Setting.Language.Select"] = "選擇語言",
            ["Hint.AppConfNotificationPolicy"] = "本應用有意不提供通知功能——研究結果表明，智慧型手機通知可能會降低與認知控制功能相關的腦神經活動：Upshaw, J.D., Shields, G.S., Judah, M.R., & Zabelina, D.L. (2023). Electrophysiological Effects of Smartphone Notifications on Cognitive Control following a Brief Mindfulness Induction. Biological psychology, 108725",
        },
        ["fr"] = new()
        {
            ["AppConf.Overwrite"] = "Gestion écrasement",
            ["AppConf.Language"] = "Langue/Language",
            ["AppConf.InitMode"] = "Mode initial",
            ["AppConf.Bypass"] = "Contournement par défaut",
            ["Setting.InitMode.IsFirstLaunch"] = "Importer outils au prochain démarrage",
            ["Setting.Bypass.SrcValidationGroup"] = "Toujours ignorer les listes de contrôle de validation source",
            ["Setting.Bypass.EncTermsValidationGroup"] = "Toujours ignorer la validation des conditions d'encodage",
            ["AppConf.Cancel"] = "Annuler",
            ["AppConf.Save"] = "Enregistrer",
            ["AppConf.ClearOldQueueJson"] = "Nettoyer l'ancienne file",
            ["AppConf.ClearOldQueueJsonTitle"] = "Nettoyer l'ancienne file",
            ["AppConf.ClearOldQueueJsonResult"] = "{0} ancien(s) fichier(s) de file supprimé(s).",
            ["AppConf.NoOldQueueJson"] = "Aucune donnée de file trouvée.",
            ["Hint.AppConfNotificationPolicy"] = "Les notifications ne sont pas fournies volontairement : des données suggèrent qu'elles peuvent réduire l'activité neuronale liée au contrôle cognitif. Upshaw, J.D., Shields, G.S., Judah, M.R., & Zabelina, D.L. (2023). Electrophysiological Effects of Smartphone Notifications on Cognitive Control following a Brief Mindfulness Induction. Biological psychology, 108725",
            ["AppConfModal.Title"] = "Paramètres 1cenc",
            ["AppConfModal.Header"] = "Paramètres",
            ["Setting.Overwrite.LongPressDivisor"] = "Diviseur appui long MB (MB÷Div=mm:ss)",
            ["Setting.Overwrite.MinLongPress"] = "Durée min. appui long (ms)",
            ["Setting.Overwrite.MaxLongPress"] = "Durée max. appui long (ms)",
            ["Setting.Language.Select"] = "Choisir langue",
            ["AppConf.Validation.Required"] = "{0} est requis.",
            ["AppConf.Validation.IntegerOnly"] = "{0} doit être un entier.",
            ["AppConf.Validation.Min"] = "{0} doit être >= {1}.",
            ["AppConf.Validation.Max"] = "{0} doit être <= {1}.",
            ["AppConf.Validation.InvalidNumericInput"] = "Seuls les chiffres sont autorisés.",
            ["AppConf.Validation.InvalidNumericInputTitle"] = "Entrée invalide",
        },
        ["es"] = new()
        {
            ["AppConf.Overwrite"] = "Gestión de sobrescritura",
            ["AppConf.Language"] = "Idioma/Language",
            ["AppConf.InitMode"] = "Modo inicial",
            ["AppConf.Bypass"] = "Omisión predeterminada",
            ["Setting.InitMode.IsFirstLaunch"] = "Auto-importar herramientas al inicio",
            ["Setting.Bypass.SrcValidationGroup"] = "Omitir siempre las listas de verificación de fuente",
            ["Setting.Bypass.EncTermsValidationGroup"] = "Omitir siempre la validación de términos de codificación",
            ["AppConf.Cancel"] = "Cancelar",
            ["AppConf.Save"] = "Guardar",
            ["AppConf.ClearOldQueueJson"] = "Limpiar ant. cola",
            ["AppConf.ClearOldQueueJsonTitle"] = "Purga datos antiguos de cola",
            ["AppConf.ClearOldQueueJsonResult"] = "{0} archivo(s) de cola antiguo(s) eliminado(s).",
            ["AppConf.NoOldQueueJson"] = "No se encontraron datos de cola.",
            ["Hint.AppConfNotificationPolicy"] = "Las notificaciones se omiten deliberadamente: hay evidencia de que pueden reducir actividad neuronal asociada al control cognitivo. Upshaw, J.D., Shields, G.S., Judah, M.R., & Zabelina, D.L. (2023). Electrophysiological Effects of Smartphone Notifications on Cognitive Control following a Brief Mindfulness Induction. Biological psychology, 108725",
            ["AppConfModal.Title"] = "Ajustes de 1cenc",
            ["AppConfModal.Header"] = "Ajustes",
            ["Setting.Overwrite.LongPressDivisor"] = "Divisor MB pulsación larga (MBtoOW÷Div=mm:ss)",
            ["Setting.Overwrite.MinLongPress"] = "Duración mín. pulsación larga (ms)",
            ["Setting.Overwrite.MaxLongPress"] = "Duración máx. pulsación larga (ms)",
            ["Setting.Language.Select"] = "Elegir idioma",
            ["AppConf.Validation.Required"] = "{0} es obligatorio.",
            ["AppConf.Validation.IntegerOnly"] = "{0} debe ser un entero.",
            ["AppConf.Validation.Min"] = "{0} debe ser >= {1}.",
            ["AppConf.Validation.Max"] = "{0} debe ser <= {1}.",
            ["AppConf.Validation.InvalidNumericInput"] = "Solo se permiten valores numéricos.",
            ["AppConf.Validation.InvalidNumericInputTitle"] = "Entrada no válida",
        },
        ["ja"] = new()
        {
            ["AppConf.Overwrite"] = "上書き処理",
            ["AppConf.Language"] = "言語/Language",
            ["AppConf.InitMode"] = "初期化モード",
            ["AppConf.Bypass"] = "デフォルトバイパス",
            ["Setting.InitMode.IsFirstLaunch"] = "次回起動時にツールを自動取込",
            ["Setting.Bypass.SrcValidationGroup"] = "常にソース検証チェックリストをバイパス",
            ["Setting.Bypass.EncTermsValidationGroup"] = "常にエンコード条件検証をバイパス",
            ["AppConf.Cancel"] = "キャンセル",
            ["AppConf.Save"] = "保存",
            ["AppConf.ClearOldQueueJson"] = "古いキューをクリーン",
            ["AppConf.ClearOldQueueJsonTitle"] = "古いキューをクリーン",
            ["AppConf.ClearOldQueueJsonResult"] = "{0} 個の古いキューファイルを削除しました。",
            ["AppConf.NoOldQueueJson"] = "キューデータが見つかりません。",
            ["Hint.AppConfNotificationPolicy"] = "通知機能は意図的に提供していません。スマートフォン通知は認知制御に関連する神経活動を低下させる可能性が示唆されています: Upshaw, J.D., Shields, G.S., Judah, M.R., & Zabelina, D.L. (2023). Electrophysiological Effects of Smartphone Notifications on Cognitive Control following a Brief Mindfulness Induction. Biological psychology, 108725",
            ["AppConfModal.Title"] = "1cenc 設定",
            ["AppConfModal.Header"] = "設定",
            ["Setting.Overwrite.LongPressDivisor"] = "長押し MB 除数 (MBtoOW÷Div=mm:ss)",
            ["Setting.Overwrite.MinLongPress"] = "最小長押し時間 (ms)",
            ["Setting.Overwrite.MaxLongPress"] = "最大長押し時間 (ms)",
            ["Setting.Language.Select"] = "言語を選択",
            ["AppConf.Validation.Required"] = "{0} は必須です。",
            ["AppConf.Validation.IntegerOnly"] = "{0} は整数である必要があります。",
            ["AppConf.Validation.Min"] = "{0} は {1} 以上である必要があります。",
            ["AppConf.Validation.Max"] = "{0} は {1} 以下である必要があります。",
            ["AppConf.Validation.InvalidNumericInput"] = "数値のみ入力できます。",
            ["AppConf.Validation.InvalidNumericInputTitle"] = "無効な入力",
        },
        ["ru"] = new()
        {
            ["AppConf.Overwrite"] = "Перезапись файлов",
            ["AppConf.Language"] = "Язык/Language",
            ["AppConf.InitMode"] = "Режим инициализации",
            ["AppConf.Bypass"] = "Обход по умолчанию",
            ["Setting.InitMode.IsFirstLaunch"] = "Автоимпорт инструментов при запуске",
            ["Setting.Bypass.SrcValidationGroup"] = "Всегда пропускать проверку исходного видео",
            ["Setting.Bypass.EncTermsValidationGroup"] = "Всегда пропускать проверку условий кодирования",
            ["AppConf.Cancel"] = "Отмена",
            ["AppConf.Save"] = "Сохранить",
            ["AppConf.ClearOldQueueJson"] = "Очист. стар. дан. очер.",
            ["AppConf.ClearOldQueueJsonTitle"] = "Очистить старые данные очереди",
            ["AppConf.ClearOldQueueJsonResult"] = "Удалено {0} старых файлов(а) очереди.",
            ["AppConf.NoOldQueueJson"] = "Данные очереди не найдены.",
            ["Hint.AppConfNotificationPolicy"] = "Уведомления намеренно не предоставляются: данные показывают, что они могут снижать нейронную активность, связанную с когнитивным контролем. Upshaw, J.D., Shields, G.S., Judah, M.R., & Zabelina, D.L. (2023). Electrophysiological Effects of Smartphone Notifications on Cognitive Control following a Brief Mindfulness Induction. Biological psychology, 108725",
            ["AppConfModal.Title"] = "Настройки 1cenc",
            ["AppConfModal.Header"] = "Настройки",
            ["Setting.Overwrite.LongPressDivisor"] = "Делитель MB длит. нажатия (MBtoOW÷Div=mm:ss)",
            ["Setting.Overwrite.MinLongPress"] = "Мин. длительность нажатия (мс)",
            ["Setting.Overwrite.MaxLongPress"] = "Макс. длительность нажатия (мс)",
            ["Setting.Language.Select"] = "Выбрать язык",
            ["AppConf.Validation.Required"] = "{0} обязательно.",
            ["AppConf.Validation.IntegerOnly"] = "{0} должно быть целым числом.",
            ["AppConf.Validation.Min"] = "{0} должно быть >= {1}.",
            ["AppConf.Validation.Max"] = "{0} должно быть <= {1}.",
            ["AppConf.Validation.InvalidNumericInput"] = "Разрешены только числовые значения.",
            ["AppConf.Validation.InvalidNumericInputTitle"] = "Недопустимый ввод",
        }
    };

    private readonly Dictionary<string, string> _d;
    public string LanguageCode { get; }

    public static AppConfLangProviderM Current => new(UILangProviderM.Current.LanguageCode);

    public string this[string key] => _d.TryGetValue(key, out var v) ? v : key;

    public AppConfLangProviderM(string languageCode)
    {
        LanguageCode = Data.ContainsKey(languageCode) ? languageCode : "en";
        _d = Data[LanguageCode];
    }
}
